title: Teejys Diary
email: "" # optional
description: "The personal diary and thoughts of Teejys, with posts, music, and more."
baseurl: "/diary" # since your repo is 'diary'
url: "https://spummy.github.io" # GitHub Pages base URL
theme: minima
plugins:
  - jekyll-feed
